# **Numpy**

**Numpy** é um pacote Python para processamento matricial (computação orientada a matriz) onde:
•	as classes e métodos são majoritariamente escrito em C, garantindo eficiência computacional
•	possui muitos recursos para computação científica e problemas de álgebra linear
Vários outros pacotes do Python dependem fortemente do numpy , como por exemplo:
•	pandas
•	matplotlib
•	sklearn

Referência: https://python-course.eu/numerical-programming/introduction-to-numpy.php



**Numpy** é um pacote, precisa portanto ser importado. A forma típica de importar o numpy é import numpy as np porém, outras formas também podem ser utilizadas, como por exemplo:

import numpy from numpy import *

A estrutura de dados base do numpy são os arrays, que funcionam de forma semelhante às listas em Python, no entanto:
* Todo elemento em um array deve ser do mesmo tipo, tipicamente um tipo numérico como float ou int
* Os arrays viabilizam a realização eficiente de operações numéricas envolvendo grandes quantidades de dados, sendo para este fim, muito mais eficientes que as listas.
* Cada dimensão de um array é chamada de eixo (axis)
* 	Os eixos são numerados a partir de 0
* Os elementos são acessados utilizando colchetes [ ] (semelhante às listas do Python)







# **Numpy - Array**

Arrays podem ser construidos de muitas formas diferentes:
* convertendo listas
* via métodos do numpy
* convertendo DataFrames


In [1]:
import numpy as np
# criando um array unidimensional a partir de uma lista
print("1D array",5*'-','\n')

lst = [1,3,5,7,9,10]
a1d = np.array(lst)
print(a1d)

# note que na impressão de um array, as vírgulas entre elementos não aparecem como no caso de listas
print(lst)


1D array ----- 

[ 1  3  5  7  9 10]
[1, 3, 5, 7, 9, 10]


In [ ]:
# Criando arrays unidimensionais a partir de métodos do numpy
b1d = np.zeros((8))  # array com oito elementos iguais a zero
print('b1d=',b1d)

c1d = np.ones((10))  # array com oito elementos iguais a um
print('c1d=',c1d)

d1d = np.arange(10)  # array com numeros entre 0 e 9
print('d1d=',d1d)

e1d = np.linspace(1,2,5) #array com 5 números igualmente espaçados no intervalo entre 1 e 2 
print('e1d=',e1d)

b1d= [0. 0. 0. 0. 0. 0. 0. 0.]
c1d= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
d1d= [0 1 2 3 4 5 6 7 8 9]
e1d= [1.   1.25 1.5  1.75 2.  ]


In [ ]:
# Criando array bidimensional (matriz) a partir de uma lista de listas
print("\n 2D array",5*'-','\n')
a2d = np.array([[1,3,5,7,9,11],
                  [2,4,6,8,10,12],
                  [0,1,2,3,4,5]])
print('a2d=\n',a2d)


 2D array ----- 

a2d=
 [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [ 0  1  2  3  4  5]]


In [ ]:
# Criando arrays ubidimensionais a partir de métodos do numpy
b2d = np.zeros((5,3))  # criando matriz 5X3 de zeros
print('b2d=\n',b2d)

c2d = np.ones((5,10))  # criando matriz 5X10 de uns
print('c2d=\n',c2d)

d2d = np.identity(3) # criando matrix identidade 3X3
print('d2d=\n',d2d)

b2d=
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
c2d=
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
d2d=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **Acessando os elementos um array**

Como no caso de sequências, os índices de um array variam de 0 a $k_i-1$, onde $k_i$ é o número de elementos na dimensão $ i $

In [ ]:
# Acessando elementos do array
# Índices variam de 0 a ki-1 em cada dimensão, onde ki é o número de elementos no dimensão i
print(a1d)
print('elemento 0 = ',a1d[0])
print('elemento de indice 3 = ',a1d[3])
print('ultimo elemento do array = ',a1d[-1]) # -1 corresponde ao último elemento do array

print(5*'-')
print(a2d)
print('linha de indice 1 = ',a2d[1]) # quando apenas um índice é fornecido 
                                     # para um array bidimensional
                                     # o que é retornado é a linha correspondente 
                                     # ao índice fornecido
            
print('elemento na linha 0 coluna 1 = ',a2d[0,1])
print('elemento na linha 1 coluna 2 = ',a2d[1,2])
print('elemento na ultima linha e ultima coluna = ',a2d[-1,-1])

[ 1  3  5  7  9 10]
elemento 0 =  1
elemento de indice 3 =  7
ultimo elemento do array =  10
-----
[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [ 0  1  2  3  4  5]]
linha de indice 1 =  [ 2  4  6  8 10 12]
elemento na linha 0 coluna 1 =  3
elemento na linha 1 coluna 2 =  6
elemento na ultima linha e ultima coluna =  5


In [ ]:
import numpy as np

A = np.array([[1,0,3],[5,4,1], [2,3,1]])
print('A=\n',A)
B = np.array([[3,1,4],[1,2,1], [3,1,1]])
print('B=\n',B)

A=
 [[1 0 3]
 [5 4 1]
 [2 3 1]]
B=
 [[3 1 4]
 [1 2 1]
 [3 1 1]]


In [ ]:
C=A+B
print('C=\n',C)

C=
 [[4 1 7]
 [6 6 2]
 [5 4 2]]


# **Multiplicação de Matrizes**

**np.dot()**

In [ ]:
D=np.dot(A,B)
print('D=\n',D)

D=
 [[12  4  7]
 [22 14 25]
 [12  9 12]]


# **Transposta de uma matriz**
A transposta de uma matriz pode ser calculada simplismente invocando o atributo .T do objeto 'ndarray'

In [ ]:
a = np.ones((5,3)) # matriz 5x3 com valores 1
print(a)
print(a.shape)

print('\nObtendo a transposta')
a_transposta = a.T
print(a_transposta)
print(a_transposta.shape)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(5, 3)

Obtendo a transposta
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)


In [ ]:
print('\nObtendo a transposta')
b_transposta = B.T
print(b_transposta)
print(b_transposta.shape)


Obtendo a transposta
[[3 1 3]
 [1 2 1]
 [4 1 1]]
(3, 3)


# **Determinante de uma matriz**

In [ ]:
determ = np.linalg.det( A )
print("%.2f" %determ)

22.00


# **Inversa de uma matriz**

In [ ]:
import math
inv = np.linalg.inv( A )
print(np.round(inv,2))
                 

[[ 0.05  0.41 -0.55]
 [-0.14 -0.23  0.64]
 [ 0.32 -0.14  0.18]]


# **Matriz identidade**

In [ ]:
d2d = np.identity(3) # criando matrix identidade 3X3
print('d2d=\n',d2d)

d2d=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **Fatiando arrays (slicing)**

A melhor forma de se percorrer um array é por meio de 'slicing', evitando o uso de laços for, que são computacionalmente muito menos eficientes.

Array slicing funciona como em listas, mas em múltiplas dimensões
Omitir um índice corresponde a recuperar toda a dimensão omitida
Um slice é uma "visão" (VIEW) do array original (similar a uma referencia), isto é, o dado não é copiado

In [ ]:
a2d = np.array([[1,3,5,7,9,11],     # criando um array bidimensional a partir de uma
                  [2,4,6,8,10,12],  # lista de listas
                  [0,1,2,3,4,5]])
print(a2d)

# slicing de colunas
print('a2d[1,:] - Recupera a linha de indice 1 (equivalent to a2d[1])\n',a2d[1,:])

# slicing de linhas
print('a2d[:,2] - Recupera a coluna de indice 2\n',a2d[:,2])

# slicing de blocos
print('a2d[1:,2:5] - Recupera o bloco a partir da linha de indice 1 e colunas 2,3 e 4\n',a2d[1:,2:5])

print('a2d[[0,2]] - Recupera as linhas 0 e 2\n',a2d[[0,2]]) 
                                                    # note que uma lista com o indice
                                                    # das linhas é passada para o slicing

print('a2d[:,[0,2,5]] - Recuperando as colunas 0,2 e 5 \n',a2d[:,[0,2,5]]) 
                                                    # note que uma lista com o indice
                                                    # das colunas é passada para o slicing

print('a2d[[0,1,2],[0,2,5]] - Recuperando os elementos das posicoes 0,0 1,2 e 2,5 \n',a2d[[0,1,2],[0,2,5]])
# quando duas listas, uma com indices de linhas e outra com indices de colunas, são passadas
# para o slicing, elementos dos pares de posicoes são recuperados. As duas listas devem
# conter o mesmo número de elementos (indices)

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [ 0  1  2  3  4  5]]
a2d[1,:] - Recupera a linha de indice 1 (equivalent to a2d[1])
 [ 2  4  6  8 10 12]
a2d[:,2] - Recupera a coluna de indice 2
 [5 6 2]
a2d[1:,2:5] - Recupera o bloco a partir da linha de indice 1 e colunas 2,3 e 4
 [[ 6  8 10]
 [ 2  3  4]]
a2d[[0,2]] - Recupera as linhas 0 e 2
 [[ 1  3  5  7  9 11]
 [ 0  1  2  3  4  5]]
a2d[:,[0,2,5]] - Recuperando as colunas 0,2 e 5 
 [[ 1  5 11]
 [ 2  6 12]
 [ 0  2  5]]
a2d[[0,1,2],[0,2,5]] - Recuperando os elementos das posicoes 0,0 1,2 e 2,5 
 [1 6 5]


# **Broadcasting**
Para garantir eficiência computacional na realização de operações entre arrays o <font color='blue'>numpy</font> utiliza um mecanismo de extensão de arrays chamado "broadcasting". Com o uso de broadcasting:
- as operações aritméticas com arrays (soma, subtração, multiplicação e divisão) são feitas elemento a elemento (*"element-wise"*)
- o __broadcasting__ transforma os arrays envolvidos nas operações aritméticas de modo que tenham as mesmas dimensões, possibilitando assim que as operações possam ser realizada elemento a elemento

```python
A = np.arange(25).reshape(5,5) # matriz 5x5
s = 3                          # escalar
B = s+A                        # matriz 5x5
```
$$
B = s + A = \left[\begin{array}{ccccc}
3 & 3 & 3 & 3 & 3\\
3 & 3 & 3 & 3 & 3\\
3 & 3 & 3 & 3 & 3\\
3 & 3 & 3 & 3 & 3\\
3 & 3 & 3 & 3 & 3
\end{array}\right] + 
\left[\begin{array}{ccccc} 
0  & 1 & 2 & 3 & 4 \\
5  & 6 & 7 & 8 & 9\\
10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19\\
20 & 21 & 22 & 23 & 24
\end{array}\right]
$$

In [ ]:
import numpy as np

# Cria uma matriz 5x5 com números aleatórios
A = np.arange(25).reshape(5,5)

# define um escalar
s = 3

# O opeador "+" é aplicado elemento por elemento (caso contrário não seria definido)
B = s + A

print(A,'\n')
print(B)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]
 [23 24 25 26 27]]


**# Broadcasting e operações entre arrays**
Broadcasting tambem é aplicado quando operações aritméticas são aplicadas em pares de arrays, porém algumas restrições devem ser respeitadas:
- Os dois arrays devem possuir dimensões compatíveis em algum(s) dos eixos
- O broadcasting é aplicado nos demais eixos para que ambos os arrays tenham as mesmas dimensões
```python
A = np.arange(25).reshape(5,5) # matriz 5x5
v = np.arange(5)               # array com 5 elementos
B = v*A                        # matriz 5x5
```
$$
B = v * A 
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccccc}
0  & 1 & 2 & 3 & 4
\end{array}\right] * 
\left[\begin{array}{ccccc} 
0  & 1 & 2 & 3 & 4 \\
5  & 6 & 7 & 8 & 9\\
10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19\\
20 & 21 & 22 & 23 & 24
\end{array}\right] 
$$

$$
\downarrow
$$

$$
\left[\begin{array}{ccccc}
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4\\
0  & 1 & 2 & 3 & 4
\end{array}\right] * 
\left[\begin{array}{ccccc} 
0  & 1 & 2 & 3 & 4 \\
5  & 6 & 7 & 8 & 9\\
10 & 11 & 12 & 13 & 14\\
15 & 16 & 17 & 18 & 19\\
20 & 21 & 22 & 23 & 24
\end{array}\right]
$$

__Cuidado__: A operação <font color='blue'>*</font> corresponde a uma multiplicação elemento por elemento, e não uma multiplicação matricial.

In [ ]:
A = np.arange(25).reshape(5,5) # matriz 5x5
print('Matriz "A" possui ', A.shape[0], ' linhas e ',A.shape[1],' colunas')


v = np.arange(5)  # array com 5 elementos
                  # como a segunda dimensão não foi especificada, "v" é interpretado 
                  # como um sendo 1x5 (uma linha e 5 colunas)
        
print('Array "v" possui ', v.shape[0], ' elementos ')
print('Note que a segunda dimensão de "v" não é especificada ',v.shape)

# A operação "*" é realizada elemento a elemento, broadcasting o array "v" para gerar novas linhas
B = v * A

print(5*'---')
print('v = \n',v)
print('A = \n',A)
print('B = \n',B)

Matriz "A" possui  5  linhas e  5  colunas
Array "v" possui  5  elementos 
Note que a segunda dimensão de "v" não é especificada  (5,)
---------------
v = 
 [0 1 2 3 4]
A = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
B = 
 [[ 0  1  4  9 16]
 [ 0  6 14 24 36]
 [ 0 11 24 39 56]
 [ 0 16 34 54 76]
 [ 0 21 44 69 96]]


# **Pandas**

__Conteúdo:__

- Pandas 
  - Séries
  - DataFrame

  
__Referencias:__

[Introduction to Pandas](https://www.ritchieng.com/pandas-introduction/)

<font color='blue'>Pandas</font> é um pacote python construído com base no <font color='blue'>numpy</font> e <font color='blue'>matplotlib</font> que busca organizar dados no formato de tabela, atribuindo rótulos às linhas e colunas. O pacote <font color='blue'>pandas</font> fornece ainda um conjunto de funcionalidades que premite processar as informações de tabelas de forma bastante eficiente, implementando métodos fundamentais para fins de tratamento de dados.

O <font color='blue'>pandas</font> organiza os dados em três tipos de estruturas:
- Series (Séries)
- DataFrame
- Panel (Paineis não serão abordados neste curso)

### <font color='blue'>Series</font>
A estrutura de representação tipo <font color='blue'>series</font> do <font color='blue'>pandas</font> é semelhante a um array unidimensional, porém os elementos podem ser indexados por números inteiros (como em um array do <font color='blue'>numpy</font>) ou por meio de rótulos (labels) que não precisam ser únicos e podem ser organizados de forma hierárquica.
- Quando os índices ou rótulos não são informados explicitamente, <font color='blue'>pandas</font> cria uma indexação com números inteiros automaticamente, variando os índices de $0$ (zero) a $n-1$, onde $n$ é o número de elementos na série.
- Os rótulos são usados para realizar buscas rápidas, alinhamento de dados e operações de junção de dados.

#### Criando séries com <font color='blue'>pandas</font>
Séries pondem ser criadas no <font color='blue'>pandas</font> de diferentes formas, a partir de:
- listas
- arrays
- dicionários
- DataFrames

In [ ]:
import pandas as pd

In [ ]:
# Criando uma série a partir de uma lista. Neste caso os índices (ou rótulos) não são fornecidos,
# então o pandas cria os índices automaticamente

lst = ['a','b','c','d','e']
series = pd.Series(lst)
print(series)

0    a
1    b
2    c
3    d
4    e
dtype: object


In [ ]:
# Criando uma série a partir de um dicionário. As chaves do dicionário se tornam os rótulos e
# os valores os elementos da série

dct = {'A' : 50, 'B' : 10, 'C' : 80, 'D' : 33} 
series = pd.Series(dct)
print(series)

A    50
B    10
C    80
D    33
dtype: int64


In [ ]:
# Carregar um CSV simples
import pandas as pd # importamos a bilbioteca

df = pd.read_csv('https://raw.githubusercontent.com/Rogerio-mack/Visualizacao-de-Dados-em-Python/main/data/tips.csv')  # o método read_csv carrega um arquivo no formato '.csv'
                                # a primeira linha do arquivo se torna os rótulos das colunas
                                # como os indices não foram especificados, são criados automaticamente

print('Rotulos das colunas')
print(df.columns.values)    # imprime o nome dos rótulos das colunas
df.head()

Rotulos das colunas
['total_bill' 'tip' 'sex' 'smoker' 'day' 'time' 'size']


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

O comando df.head() permite exibir o aspecto inicial dos dados a partir de suas primeiras linhas.

# **Selecionando Dados**
Seleções dos dados são bastante importantes. Você nem sempre estará interessado em exibir ou analisar todos os dados. Por exemplo, você pode ter dados de produção de várias unidades de uma fábrica, mas estar interessado somente em dados das unidades de São Paulo (seleção de linhas ou casos). Ou, você pode ter dados de vendas com diversas informações dos produtos (cor, modelo etc.) e dos clientes (nome, CPF etc.) e querer apenas dados de peso e dimensões do produto, e da origem e destino da compra para analisar os preços de frete (seleção de colunas ou atributos). Mais frequentemente ainda você vai realizar as duas seleções criando slices dos dados.


# **Selecionando colunas de dados com o pd.Series**

In [ ]:
print(df.tip)
# ou
# print(df['tip'])

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


# **Selecionando uma ou Mais Colunas com o pd.DataFrame**

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
selected_df = df[['total_bill', 'tip', 'size']]

selected_df.head() # um novo dataframe com atributos selecionados

total_bill   tip  size
0       16.99  1.01     2
1       10.34  1.66     3
2       21.01  3.50     3
3       23.68  3.31     2
4       24.59  3.61     4

# **Selecionar Linhas**

In [ ]:
df_nao_fumantes = df[ df.smoker == 'No' ]
df_fumantes = df[ df.smoker == 'Yes' ]
df_nao_fumantes.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df_fumantes.head()


total_bill   tip   sex smoker  day    time  size
56       38.01  3.00  Male    Yes  Sat  Dinner     4
58       11.24  1.76  Male    Yes  Sat  Dinner     2
60       20.29  3.21  Male    Yes  Sat  Dinner     2
61       13.81  2.00  Male    Yes  Sat  Dinner     2
62       11.02  1.98  Male    Yes  Sat  Dinner     2

# **Seleção de Linhas e Colunas**

O uso mais geral das seleções é quando fazemos seleções de linhas e colunas dos dados, e às vezes nos referimos a esse subconjunto dos dados de slice (fatia) dos dados.

In [ ]:
df[ df.smoker == 'Yes' ]['tip'].mean() > df[ df.smoker == 'No' ]['tip'].mean() 

True

# **Exercícios:**

1) Crie um array de 10 elementos. Altere o valores de todos os elementos com índices 5 até 8 para 0.

In [22]:
import numpy as np
lst = np.arange(10)
a1d = np.array(lst)
lst[5:9]=0 #perceba que colocamos até o 9 para ele pegar até o 8
print(lst)

[0 1 2 3 4 0 0 0 0 9]


2) Crie um array com 3 linhas e 2 colunas. Depois imprima o shape e a 2ª linha da matriz.

In [30]:
import numpy as np
a2d = np.array([[1,3],
                  [2,4], [4,2]])
print('a2d=\n',a2d)
print(a2d[1])

a2d=
 [[1 3]
 [2 4]
 [4 2]]
[2 4]


3) Ler e exibir  o arquivo insect.csv

In [13]:
import pandas as pd 

df = pd.read_csv('c://Users/unifgscopel/Documents/insect.csv')

print(df)

    count spray
0      10     A
1       7     A
2      20     A
3      14     A
4      14     A
..    ...   ...
67     10     F
68     26     F
69     26     F
70     24     F
71     13     F

[72 rows x 2 columns]


4) Exibir somente os elementos do arquivo insect com spray E

In [31]:
import pandas as pd 

df = pd.read_csv('c://Users/unifgscopel/Documents/insect.csv')
df_spraF = df[df.spray == "E"]
print(df_spraF)


    count spray
48      3     E
49      5     E
50      3     E
51      5     E
52      3     E
53      6     E
54      1     E
55      1     E
56      3     E
57      2     E
58      6     E
59      4     E


In [ ]:
#5. Dada a matriz A = [[-2,4,7,8],[3,5,6,9],[1,0,-2,4]] calcular a inversa

In [2]:
import numpy as np
from math import *
matriz =np.array([[-2,4,7,8],[3,5,6,9],[1,0,-2,4]])
inv = np.linalg.inv( matriz )
print(np.round(inv,2))

#Deve dar erro já que a matriz não é quadrada, então não podemos calcular a inversa

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
#6)dada a matriz b=[[1,3,3],[-8,10,9],[1,3,4]] calcule o determinante
#e a inversa

In [28]:
import numpy as np
from math import *
matriz = np.array([[1,3,3],[-8,10,9],[1,3,4]])
determ = np.linalg.det( matriz )
print("%.2f" %determ)
inv = np.linalg.inv( matriz )
print(np.round(inv,2))

34.00
[[ 0.38 -0.09 -0.09]
 [ 1.21  0.03 -0.97]
 [-1.    0.    1.  ]]


In [ ]:
#7)Calcular AxB e BxA

In [35]:
import numpy as np
from math import *
A =np.array([[-2,4,7,8],[3,5,6,9],[1,0,-2,4]])
B = np.array([[1,3,3],[-8,10,9],[1,3,4]])
D=np.dot(B,A)
print('D=\n',D)
#não é possível multiplicar a por b 

D=
 [[ 10  19  19  47]
 [ 55  18 -14  62]
 [ 11  19  17  51]]
